### ISSUE TITLE
arm-nn link error

### ISSUE THREAD

**Issue by Wayne-pw** [ARM-software/armnn#9] opened 2018-04-13 09:30 UTC
hello
    I compiled armnn for errors in the link process
/boost_1_64_0/stage/lib/libboost_unit_test_framework.a(unit_test_main.o): In function `boost::unit_test::unit_test_main(boost::unit_test::test_suite* (*)(int, char**), int, char**)':
unit_test_main.cpp:(.text+0xec): undefined reference to `stdin'
unit_test_main.cpp:(.text+0xf0): undefined reference to `stdin'
unit_test_main.cpp:(.text+0xf8): undefined reference to `_IO_getc'
/boost_1_64_0/stage/lib/libboost_unit_test_framework.a(execution_monitor.o): In function `boost::detail::signal_handler::~signal_handler()':
execution_monitor.cpp:(.text+0x104): undefined reference to `__errno_location'
/boost_1_64_0/stage/lib/libboost_unit_test_framework.a(execution_monitor.o): In function `boost::system_error::system_error(char const*)':
execution_monitor.cpp:(.text+0x390): undefined reference to `__errno_location'
libarmnnCaffeParser.so: undefined reference to `google::protobuf::internal::WireFormat::SerializeUnknownFields(google::protobuf::UnknownFieldSet const&, google::protobuf::io::CodedOutputStream*)'
libarmnnCaffeParser.so: undefined reference to `google::protobuf::Message::SpaceUsed() const'
libarmnnCaffeParser.so: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::string const&) const'
libarmnnCaffeParser.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilTotalBytesLimit() const'
libarmnnCaffeParser.so: undefined reference to `google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int)'

**Comment by MatthewARM** [comment] 2018-04-13 10:29
Hi @Wayne-pw please could you share information about what platform you are compiling for, and the tools that you are using. Also, please could you share what cmake options you are using.

Thanks,

Matthew

**Comment by Wayne-pw** [comment] 2018-04-14 03:31
I compile program to run run on Android 64 bit platform. I compile boost with aarch64-linux-gnu-gcc-4.9, arm-nn sdk and protoc with android-ndk-r16b.
cmake option:
export CXX=android-ndk-r16b/android-ndk-standalone_aarch64/bin/aarch64-linux-android-clang++
export CC=android-ndk-r16b/android-ndk-standalone_aarch64/bin/aarch64-linux-android-clang
cmake-3.10.2/bin/cmake -DARMCOMPUTE_ROOT=ComputeLibrary-master -DARMCOMPUTE_BUILD_DIR=/ComputeLibrary-master/build -DBOOST_ROOT=boost_1_64_0 -DCAFFE_GENERATED_SOURCES=caffe-master/build/src/ -DPROTOBUF_LIBRARY_DEBUG=ProtobufBuild/libs/arm64-v8a/ and -DPROTOBUF_LIBRARY_RELEASE=ProtobufBuild/libs/arm64-v8a/ -DBUILD_CAFFE_PARSER=1 -DARMCOMPUTENEON=1 ..

**Comment by MatthewARM** [comment] 2018-04-16 09:08
Hi @Wayne-pw the problem is you are compiling boost for linux, then linking with other stuff built for Android.

Please build boost for android using the same ndk compiler that you are using for everything else.

Hope that helps,

Matthew

**Comment by MatthewARM** [comment] 2018-04-16 10:32
Hi @Wayne-pw where you have "-DPROTOBUF_LIBRARY_RELEASE=ProtobufBuild/libs/arm64-v8a/", use the full path to the library (libprotobuf.so), not just the path to the directory.

Hope that helps,

Matthew

**Comment by Wayne-pw** [comment] 2018-04-16 12:08
you mean PROTOBUF_LIBRARY_RELEASE use the path to code path or the other path?
can you tell me how to set up the path to PROTOBUF_LIBRARY_RELEASE

**Comment by MatthewARM** [comment] 2018-04-16 12:29
Hi @Wayne-pw I mean that PROTOBUF_LIBRARY_RELEASE is set to the full path to the library. For example on my computer it is `/home/MatthewARM/install/aarch64/protobuf/lib/libprotobuf.so`

**Comment by Wayne-pw** [comment] 2018-04-17 02:09
I set the path in your way, the mistake still exists

**Comment by MatthewARM** [comment] 2018-04-25 08:16
Hi @Wayne-pw I hope you were able to solve the problem. I'll close this ticket for now, but if you are still having trouble please re-open it.

All the best,
Matthew

**Closed by MatthewARM** 2018-04-25 08:16 UTC
