### ISSUE TITLE
FullyConnectedLayer: TensorShape set on OutputSlot[0] does not match the inferred shape. : [1,20,2] != [1,2]

### ISSUE THREAD

**Issue by QHenry1990** [ARM-software/armnn#714] opened 2023-01-18 07:59 UTC
when I use onnx model,the output dimension and elements are all right, like this:(std::cout<<"output size = "<<outputBinding.second.GetNumElements()<<std::endl;),but when I use armnn::IRuntime::CreationOptions options; there is an error :
terminate called after throwing an instance of 'armnn::LayerValidationException'
  what():  FullyConnectedLayer: TensorShape set on OutputSlot[0] does not match the inferred shape. : [1,20,2] != [1,2]

the model is very simple by pytorch linear layer, input is [1,20,8],output is [1,20,2]

**Comment by FrancisMurtagh-arm** [comment] 2023-01-18 14:00
Hi @QHenry1990,

Can you provide the Onnx model to help us reproduce the issue?

Regards,
Francis.

**Comment by QHenry1990** [comment] 2023-01-19 01:04
> Hi @QHenry1990,
> 
> Can you provide the Onnx model to help us reproduce the issue?
> 
> Regards, Francis.

OK, 
[model1.zip](https://github.com/ARM-software/armnn/files/10452462/model1.zip)

**Comment by FrancisMurtagh-arm** [comment] 2023-01-19 13:55
Hi @QHenry1990,

I've reproduced the issue and am now looking into it.

Thanks,
Francis.

**Comment by matthewsloyanARM** [comment] 2023-02-16 17:21
Hi @QHenry1990, 

I have created a fix for this issue here: https://review.mlplatform.org/c/ml/armnn/+/9170. Can you please apply this patch and see if it works for you?

Thanks again for letting us know about it. All the best!

Kind regards,

Matthew

**Comment by QHenry1990** [comment] 2023-02-20 01:40
thanks a lot!

**Comment by matthewsloyanARM** [comment] 2023-02-20 12:33
Hi @QHenry1990, 

This fix has now been merged to the main branch so you can get it there. It unfortunately won't make it into the upcoming release (23.02) but it will be in the next one (23.05).

I will close this issue now because it has been fixed. Thanks again for letting us know about it. All the best!

Kind regards,

Matthew

**Closed by matthewsloyanARM** 2023-02-20 12:33 UTC
Labels: Bug
