### ISSUE TITLE
half-precision inference

### ISSUE THREAD

**Issue by juncheolye** [ARM-software/armnn#363] opened 2020-03-13 08:01 UTC
Hello!
I built armnn in my android phone.
And I'm trying to run some examples in this repo(https://github.com/ARM-software/ML-examples/tree/master/armnn-mnist).
mnist_tf.cpp example in this repo works well!

But When I'm trying to do half-precision inference, It's not work!

`armnn::IRuntime::CreationOptions options;`
`armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);`
` armnn::OptimizerOptions suboptions;`
`suboptions.m_ReduceFp32ToFp16 = true;`
`armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuRef}, runtime->GetDeviceSpec(), suboptions);`

This is my part of the code I modified.

Please comment.
Thanks!

**Comment by juncheolye** [comment] 2020-03-13 10:13
Hello! 
I found something in debug mode.

> { "layerGuid": 2, "layerName": "add", "outputSlot": 0, "shape": [1, 10], "min": -104137, "max": 92946, "data": [[1388.74, -104137, -12244.3, 81630.9, -35435.1, 281.557, -89243.8, 92946, 17242.7, 47570.6]] }

> { "layerGuid": 3, "layerName": "Softmax", "outputSlot": 0, "shape": [1, 10], "min": 0, "max": 1, "data": [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]] }

This is 32-bit floating point.

> { "layerGuid": 2, "layerName": "add", "outputSlot": 0, "shape": [1, 10], "min": -inf, "max": inf, "data": [[1390, -inf, -12240, inf, -35424, 266.5, -inf, inf, 17248, 47584]] }

> { "layerGuid": 3, "layerName": "Softmax", "outputSlot": 0, "shape": [1, 10], "min": nan, "max": nan, "data": [[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]] }

> { "layerGuid": 10, "layerName": "convert_fp16_to_fp32-0-Softmax", "outputSlot": 0, "shape": [1, 10], "min": nan, "max": nan, "data": [[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]] }

This is 16-bit floating point result.

I think this problem was caused by out of 16-bit precision range.

It this right?

**Comment by FrancisMurtagh-arm** [comment] 2020-03-18 10:11
Hi @juncheolye,

I'm looking into reproducing this now.

Francis.

**Comment by juncheolye** [comment] 2020-03-18 11:59
Hi @FrancisMurtagh-arm,
I have one more question.
What kind of binary files does TfParser(Not TfliteParser) use?
normal pb file or frozen pb file?

**Comment by FrancisMurtagh-arm** [comment] 2020-03-18 12:21
Hi @juncheolye,

We use both .pb files.

Regards,
Francis.

**Comment by MatthewARM** [comment] 2020-03-18 12:27
The parser doesn't support a lot of training-only stuff, so if recommend freezing, and if possible "optimise for inference" which used to be a script available in Tensirflow somewhere but I'm not sure if it's still in the latest Tensirflow.

**Comment by juncheolye** [comment] 2020-03-19 02:10
Thanks @MatthewARM 
As you said, I convert pb file to optimize version pb file using optimize for inference.

But I have this error.

> terminating with uncaught exception of type armnn::ParseException: Unsupported operation AddV2 in tensorflow::GraphDef  at function LoadNodeDef

Is tensorflow version problem?

Thanks!

**Comment by MatthewARM** [comment] 2020-03-19 09:23
I've checked the documentation real quick:
https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/src/armnnTfLiteParser/TensorFlowLiteSupport.md
https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/src/armnnTfParser/TensorFlowSupport.md

It looks like conv2d_transpose is not in the Tensorflow or Tensorflow Lite parsers. I believe it is supported on the Arm NN API though so it shouldn't be too hard to add, I'll create a ticket.

The error about "Tensor dimensionSizes must not be NULL" I've not seen before. Could be that the network uses a dynamic-sized tensor, (which is not supported and might be being misparsed)?

**Comment by juncheolye** [comment] 2020-03-19 10:27
Thanks for reply!  @MatthewARM
I think this is because of conv2d_transpose layer.
I use conv2d_transpose layer. So TfParser cannot find this components and make that errors.

I think TRANSEPOSE_CONV in TensorFlowLiteSupport.md is the same as conv2d_transpose in tensorflow. Is this right?

So currently I'm building TfLiteParser for Android in x86 system.
I followed this post #83.

But I have these errors.

> [ 67%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/Arm_TestInvalid10_backend.dir/TestDynamicBackend.cpp.o
[ 68%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/InvalidTestDynamicBackend4.dir/TestDynamicBackend.cpp.o
[ 68%] Building CXX object CMakeFiles/GatordMock.dir/tests/profiling/gatordmock/GatordMockMain.cpp.o
[ 68%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/InvalidTestDynamicBackend7.dir/TestDynamicBackend.cpp.o
[ 68%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/InvalidTestDynamicBackend6.dir/TestDynamicBackend.cpp.o
[ 68%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/InvalidTestDynamicBackend3.dir/TestDynamicBackend.cpp.o
[ 68%] Building CXX object src/armnnTfLiteParser/CMakeFiles/armnnTfLiteParser.dir/TfLiteParser.cpp.o
[ 68%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/InvalidTestDynamicBackend2.dir/TestDynamicBackend.cpp.o
[ 69%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/InvalidTestDynamicBackend1.dir/TestDynamicBackend.cpp.o
[ 69%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/InvalidTestDynamicBackend5.dir/TestDynamicBackend.cpp.o
[ 70%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/Arm_TestInvalid8_backend.dir/TestDynamicBackend.cpp.o
[ 70%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/Arm_TestValid3_backend.dir/TestDynamicBackend.cpp.o
[ 70%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/Arm_TestValid2_backend.dir/TestDynamicBackend.cpp.o
[ 70%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/ValidTestDynamicBackend.dir/TestDynamicBackend.cpp.o
[ 70%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/Arm_TestInvalid11_backend.dir/TestDynamicBackend.cpp.o
[ 70%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/Arm_TestValid4_backend.dir/TestDynamicBackend.cpp.o
In file included from /home/intern/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:6:
In file included from /home/intern/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.hpp:11:
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:8: error: 
      ISO C++ forbids forward references to 'enum' types
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
       ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:32: error: 
      field has incomplete type 'enum FlatBuffersVTableOffset'
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
                               ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:8: note: 
      forward declaration of 'tflite::FlatBuffersVTableOffset'
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
       ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2601:61: error: 
      use of undeclared identifier 'VT_CUSTOM'
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_CUSTOM);
                                                            ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2604:12: error: 
      cannot initialize object parameter of type 'const flatbuffers::Table' with
      an expression of type 'const tflite::CustomQuantization'
    return VerifyTableStart(verifier) &&
           ^~~~~~~~~~~~~~~~
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2605:35: error: 
      use of undeclared identifier 'VT_CUSTOM'
           VerifyOffset(verifier, VT_CUSTOM) &&
                                  ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2618:40: error: 
      no member named 'VT_CUSTOM' in 'tflite::CustomQuantization'
    fbb_.AddOffset(CustomQuantization::VT_CUSTOM, custom);
                   ~~~~~~~~~~~~~~~~~~~~^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2666:32: error: 
      field has incomplete type 'enum FlatBuffersVTableOffset'
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
                               ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:8: note: 
      forward declaration of 'tflite::FlatBuffersVTableOffset'
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
       ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2676:59: error: 
      use of undeclared identifier 'VT_MIN'
    return GetPointer<const flatbuffers::Vector<float> *>(VT_MIN);
                                                          ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2679:59: error: 
      use of undeclared identifier 'VT_MAX'
    return GetPointer<const flatbuffers::Vector<float> *>(VT_MAX);
                                                          ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2682:59: error: 
      use of undeclared identifier 'VT_SCALE'
    return GetPointer<const flatbuffers::Vector<float> *>(VT_SCALE);
                                                          ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2685:61: error: 
      use of undeclared identifier 'VT_ZERO_POINT'
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_ZERO_POINT);
                                                            ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2688:63: error: 
      use of undeclared identifier 'VT_DETAILS_TYPE'
    return static_cast<QuantizationDetails>(GetField<uint8_t>(VT_DETAILS...
                                                              ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2691:37: error: 
      use of undeclared identifier 'VT_DETAILS'
    return GetPointer<const void *>(VT_DETAILS);
                                    ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2698:30: error: 
      use of undeclared identifier 'VT_QUANTIZED_DIMENSION'
    return GetField<int32_t>(VT_QUANTIZED_DIMENSION, 0);
                             ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2701:12: error: 
      cannot initialize object parameter of type 'const flatbuffers::Table' with
      an expression of type 'const tflite::QuantizationParameters'
    return VerifyTableStart(verifier) &&
           ^~~~~~~~~~~~~~~~
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2702:35: error: 
      use of undeclared identifier 'VT_MIN'
           VerifyOffset(verifier, VT_MIN) &&
                                  ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2704:35: error: 
      use of undeclared identifier 'VT_MAX'
           VerifyOffset(verifier, VT_MAX) &&
                                  ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2706:35: error: 
      use of undeclared identifier 'VT_SCALE'
           VerifyOffset(verifier, VT_SCALE) &&
                                  ^
/home/intern/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema_generated.h:2708:35: error: 
      use of undeclared identifier 'VT_ZERO_POINT'
           VerifyOffset(verifier, VT_ZERO_POINT) &&
                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/armnnTfLiteParser/CMakeFiles/armnnTfLiteParser.dir/TfLiteParser.cpp.o] Error 1
make[1]: *** [src/armnnTfLiteParser/CMakeFiles/armnnTfLiteParser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Linking CXX executable GatordMock
[ 70%] Linking CXX shared module backendsTestPath9/Arm_TestInvalid10_backend.so
[ 71%] Linking CXX shared module testDynamicBackend/libInvalidTestDynamicBackend7.so
[ 71%] Built target GatordMock
[ 71%] Built target Arm_TestInvalid10_backend
[ 71%] Built target InvalidTestDynamicBackend7
[ 71%] Linking CXX shared module testDynamicBackend/libInvalidTestDynamicBackend6.so
[ 71%] Linking CXX shared module testDynamicBackend/libInvalidTestDynamicBackend4.so
[ 71%] Linking CXX shared module testDynamicBackend/libInvalidTestDynamicBackend3.so
[ 71%] Linking CXX shared module backendsTestPath5/Arm_TestValid2_backend.so
[ 71%] Linking CXX shared module backendsTestPath9/Arm_TestInvalid11_backend.so
[ 71%] Built target InvalidTestDynamicBackend6
[ 71%] Linking CXX shared module testDynamicBackend/libInvalidTestDynamicBackend5.so
[ 71%] Built target InvalidTestDynamicBackend4
[ 71%] Linking CXX shared module testDynamicBackend/libInvalidTestDynamicBackend2.so
[ 71%] Linking CXX shared module testDynamicBackend/libValidTestDynamicBackend.so
[ 71%] Linking CXX shared module backendsTestPath6/Arm_TestValid4_backend.so
[ 71%] Linking CXX shared module backendsTestPath5/Arm_TestInvalid8_backend.so
[ 72%] Linking CXX shared module backendsTestPath5/Arm_TestValid3_backend.so
[ 72%] Built target InvalidTestDynamicBackend3
[ 72%] Built target Arm_TestInvalid11_backend
[ 72%] Linking CXX shared module testDynamicBackend/libInvalidTestDynamicBackend1.so
[ 72%] Built target Arm_TestValid2_backend
[ 72%] Built target InvalidTestDynamicBackend5
[ 72%] Built target InvalidTestDynamicBackend2
[ 72%] Built target ValidTestDynamicBackend
[ 72%] Built target Arm_TestValid4_backend
[ 72%] Built target Arm_TestValid3_backend
[ 72%] Built target Arm_TestInvalid8_backend
[ 72%] Built target InvalidTestDynamicBackend1
make: *** [all] Error 2



And my build command is this.

> $ CXX=aarch64-linux-android-clang++ CC=aarch64-linux-android-clang CXX_FLAGS="-fPIE -fPIC" cmake .. -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$HOME/armnn-devenv/toolchains/aarch64-android-r17b/ -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DTF_LITE_GENERATED_PATH=$HOME/armnn-devenv/google/tensorflow/tensorflow/lite/schema -DBUILD_TF_LITE_PARSER=1 -DFLATBUFFERS_INCLUDE_PATH=$HOME/armnn-devenv/google/flatbuffers/include/ -DFLATBUFFERS_LIBRARY=$HOME/armnn-devenv/google/flatbuffers/android/obj/local/arm64-v8a/libFlatBufferTest.so -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/ -DFLATBUFFERS_ROOT=$HOME/armnn-devenv/google/flatbuffers

Please help for this.

**Comment by juncheolye** [comment] 2020-03-19 12:07
Oh, I resolve build problem.
It's because of version of flatbuffers.

Only left transpose_conv....

Thanks

**Comment by MatthewARM** [comment] 2020-03-19 12:24
Ah, you're right, TRANSPOSE_CONV is the tflite name for conv2d_transpose. So that should all be working.

**Comment by FrancisMurtagh-arm** [comment] 2020-03-23 09:59
> Hello!
> I found something in debug mode.
> 
> > { "layerGuid": 2, "layerName": "add", "outputSlot": 0, "shape": [1, 10], "min": -104137, "max": 92946, "data": [[1388.74, -104137, -12244.3, 81630.9, -35435.1, 281.557, -89243.8, 92946, 17242.7, 47570.6]] }
> 
> > { "layerGuid": 3, "layerName": "Softmax", "outputSlot": 0, "shape": [1, 10], "min": 0, "max": 1, "data": [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]] }
> 
> This is 32-bit floating point.
> 
> > { "layerGuid": 2, "layerName": "add", "outputSlot": 0, "shape": [1, 10], "min": -inf, "max": inf, "data": [[1390, -inf, -12240, inf, -35424, 266.5, -inf, inf, 17248, 47584]] }
> 
> > { "layerGuid": 3, "layerName": "Softmax", "outputSlot": 0, "shape": [1, 10], "min": nan, "max": nan, "data": [[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]] }
> 
> > { "layerGuid": 10, "layerName": "convert_fp16_to_fp32-0-Softmax", "outputSlot": 0, "shape": [1, 10], "min": nan, "max": nan, "data": [[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]] }
> 
> This is 16-bit floating point result.
> 
> I think this problem was caused by out of 16-bit precision range.
> 
> It this right?

Hi @juncheolye,

Just to confirm you are correct that this is out of range and so is not a valid test case with those values.

Francis.

**Comment by MikeJKelly** [comment] 2020-04-02 18:57
Hi @juncheolye 

I think this has been resolved? 

Can you close the issue if everything's OK? Thanks!

**Comment by james-conroy-arm** [comment] 2020-06-26 10:12
Hi @juncheolye ,

Please let us know if your issue is resolved.

Cheers,
James

**Comment by james-conroy-arm** [comment] 2020-07-03 10:07
Hi @juncheolye ,

Since we have not heard back from you in a while and the issue appears to be resolved now, we are going to close this issue.

Please let us know if this is being closed in error, or feel free to open a new issue if another one should arise.

Cheers,
James

**Closed by james-conroy-arm** 2020-07-03 10:07 UTC
Labels: TIME WAIT
