### ISSUE TITLE
ArmnnConverter & ExecuteNetwork Usage

### ISSUE THREAD

**Issue by AnPay** [ARM-software/armnn#164] opened 2019-04-01 10:31 UTC
Hello
I am trying to execute ExecuteNetwork and check the output with tf model and converted tf model to armnn format model
1)I used ArmnnConverter tool to convert a tf model to armnn format.
Command used in adb shell: 
#./ArmnnConverter -f tensorflow-binary -m mobilenet_v1_1.0_224_frozen.pb -i input -o MobilenetV1/Predictions/Reshape_1 -p output -s 1,224,224,3
Input model :           17MB    mobilenet_v1_1.0_224_frozen.pb
Output generated : 16MB     output
3)Run Execute Network:
command used in adb shell:
#./ExecuteNetwork -f **tensorflow-binary** -m output  -i input -o MobilenetV1/Predictions/Reshape_1 -d your_file.txt  -s 1,224,224,3
Runs fine, prints tensors
#./ExecuteNetwork -f **armnn-binary** -m output  -i input -o MobilenetV1/Predictions/Reshape_1 -d your_file.txt  -s 1,224,224,3
**Error occurred:**
flatbuffers/include/flatbuffers/flatbuffers.h:244: flatbuffers::Vector::return_type flatbuffers::Vector<flatbuffers::Offset<armnnSerializer::AnyLayer> >::Get(flatbuffers::uoffset_t) const [T = flatbuffers::Offset<armnnSerializer::AnyLayer>]: assertion "i < size()" failed
Aborted

The input "your_file.txt" is a flat array as mentioned in the help. It gives output when run with tf model and fails when executed with converted armnn format model.
**On debugging it's found that layer_index received from flatbuffer comes to be 65 which is equal to size(), thus it fails.**
`for (unsigned int i=0; i<numInputs; ++i)
   {
       auto inputId = CHECKED_NON_NEGATIVE(static_cast<int32_t>
                                          (layer->inputSlots()->Get(i)->connection()->sourceLayerIndex()));
       std::cout<<"inputId = "<<inputId<<"\n";
       result[i] = GetBaseLayer(graphPtr, inputId)->outputSlots()->Get(0)->tensorInfo();
   }`

`return_type Get(uoffset_t i) const {
     printf("i = %lu size = %lu\n",i,size());
    FLATBUFFERS_ASSERT(i < size());
    return IndirectHelper<T>::Read(Data(), i);}`

**Commands used to build:**
`CXX=aarch64-linux-android-clang++  CC=aarch64-linux-android-clang  CXX_FLAGS="-fPIE -fPIC"  cmake ..   -DCMAKE_SYSTEM_NAME=Android   -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a   -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$ARMNNDEV/armnn-devenv/toolchains/aarch64-android-r17b/   -DCMAKE_EXE_LINKER_FLAGS="-pie -llog"   -DARMCOMPUTE_ROOT=$ARMNNDEV/armnn-devenv/ComputeLibrary/   -DARMCOMPUTE_BUILD_DIR=$ARMNNDEV/armnn-devenv/ComputeLibrary/build   -DBOOST_ROOT=$ARMNNDEV/armnn-devenv/boost   -DBOOST_LIBRARYDIR=$ARMNNDEV/armnn-devenv/boost/install/lib   -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1   -DTF_GENERATED_SOURCES=$ARMNNDEV/armnn-devenv/google/tf_pb/   -DPROTOBUF_ROOT=$ARMNNDEV/armnn-devenv/google/arm64_pb_install/   -DBUILD_TF_PARSER=1 -DBUILD_ARMNN_SERIALIZER=1   -DFLATBUFFERS_INCLUDE_PATH=$ARMNNDEV/armnn-devenv/flatbuffers/include   -DFLATBUFFERS_LIBRARY=$ARMNNDEV/armnn-devenv/flatbuffers/libflatbuffers.a   -DFLATC_DIR=$ARMNNDEV/armnn-devenv/flatbuffers  -DBUILD_TESTS=1

make -j16`

**PS**:your_file.txt looks something like this
0.681499082012 0.499423481863 0.699091174772 0.347890541798 0.893059256075 0.317762455033 0.238925760309 0.746247963743 0.35862938172 0.185409617886 0.0963199513358 0.583821514589 0.715978418217 0.991755379755 0.105288722455 0.318981731734 0.335481982383 0.706489821327 0.255523476279 0.136378250727 0.502332637656 0.580274818251 0.677454173864 0.548721022376 0.634912211285 0.335890986317 0.617197312224 0.145951839611 0.355783924735 0.659216082256 0.869394206999 0.368164179929 0.0682292530453 0.503974507163 0.954484705829 0.168305336361 0.740921782432 0.819585411381 0.21105322593 0.412600188305 0.632743876906 0.450042617085 0.332793748337 0.642172075798 0.564949086776 0.608918564187 0.726845569615 0.260

Please let me know what is going wrong? Didn't convert model properly, not executing Execute Network properly...

**Comment by MatthewARM** [comment] 2019-04-01 12:28
Sorry to hear you're having trouble. That does look like there might be a bug. We'll try to reproduce internally and figure out what is going wrong.

**Comment by AnPay** [comment] 2019-04-02 04:20
Thanks @MatthewARM .
Do we have a sample  model and a converted model in the repo for testing?

**Comment by MatthewARM** [comment] 2019-04-02 10:33
Hi @AnPay there isn't a model in the repo. We're testing with a variety of models downloaded from the internet. Because those models are big, and the copyright doesn't belong to us we don't put them in the armnn repo.

It's a good suggestion to have some simple test cases checked in though, I'll raise that internally.

For testing with tensorflow we are using inception v3 from Google's hosted models repository:

`ArmnnConverter -f tensorflow-binary -m /devenv/models/inception_v3_2016_08_28_frozen.pb -i input -s 1,299,299,3 -o InceptionV3/Predictions/Reshape_1 -p jenkins/Resources/convertedFilesDir/inception_v3_2016_08_28_frozen.armnn`

`ExecuteNetwork -f tensorflow-binary -m /devenv/models/inception_v3_2016_08_28_frozen.pb -i input -o InceptionV3/Predictions/Reshape_1 -d jenkins/Resources/Dog_299x299.snpy -s 1,299,299,3 -c CpuRef`

`ExecuteNetwork -f armnn-binary -m jenkins/Resources/convertedFilesDir/inception_v3_2016_08_28_frozen.armnn -i input -o InceptionV3/Predictions/Reshape_1 -d jenkins/Resources/Dog_299x299.snpy -s 1,299,299,3 -c CpuRef`

Then we compare the output of ExecuteNetwork to make sure that the output tensor is identical.

We're continuing to investigate why you might be hitting the FLATBUFFERS_ASSERT thing. There's quite a few Github users who are seeing the same problem now

Hope that helps,
Matthew

**Comment by AnPay** [comment] 2019-04-03 06:14
Thanks a lot @MatthewARM for such detailed response
But I am afraid I am still facing the issue.

> inputId = 1527
GetBaseLayer  ARMNN/armnn-devenv/armnn/src/armnnDeserializer/Deserializer.cpp
layerIndex = 1527
Get
i = 1527 size = 1528
layerType = 9 layer_index= 1527
layer = output layerIndex = 1527
Get
i = 1527 size = 1528
Get
i = 0 size = 0
ARMNN/armnn-devenv/flatbuffers/include/flatbuffers/flatbuffers.h:244: flatbuffers::Vector::return_type flatbuffers::Vector<flatbuffers::Offset<armnnSerializer::OutputSlot> >::Get(flatbuffers::uoffset_t) const [T = flatbuffers::Offset<armnnSerializer::OutputSlot>]: assertion "i < size()" failed
Aborted

I did exactly what u did.
Just to be on the same page, i am running these commands on the device.
Could there be an issue with libflatbuffers.a?

**Comment by AnPay** [comment] 2019-04-03 12:39
Hi @MatthewARM 
Could run it successfully now. But not on the released code.  I pulled the latest code from mlplatform(where caffe parser is also supported).
Commands:

> CXX_FLAGS="-fPIE -fPIC"  cmake ..   -DCMAKE_SYSTEM_NAME=Android   -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a   -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$ARMNNDEV/armnn-devenv/toolchains/aarch64-android-r17b/   -DCMAKE_EXE_LINKER_FLAGS="-pie -llog"   -DARMCOMPUTE_ROOT=$ARMNNDEV/armnn-devenv/ComputeLibrary/   -DARMCOMPUTE_BUILD_DIR=$ARMNNDEV/armnn-devenv/ComputeLibrary/build   -DBOOST_ROOT=$ARMNNDEV/armnn-devenv/boost   -DBOOST_LIBRARYDIR=$ARMNNDEV/armnn-devenv/boost/install/lib   -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1   -DTF_GENERATED_SOURCES=$ARMNNDEV/armnn-devenv/google/tf_pb/   -DPROTOBUF_ROOT=$ARMNNDEV/armnn-devenv/google/arm64_pb_install/   -DBUILD_TF_PARSER=1 -DBUILD_ARMNN_SERIALIZER=1   -DFLATBUFFERS_INCLUDE_PATH=$ARMNNDEV/armnn-devenv/flatbuffers/include   -DFLATBUFFERS_LIBRARY=$ARMNNDEV/armnn-devenv/flatbuffers/libflatbuffers.a   -DFLATC_DIR=$ARMNNDEV/armnn-devenv/flatbuffers  -DBUILD_CAFFE_PARSER=1

>make -j32

Could execute inception and mobilenet models(tf->armnn converted models).
Couldn't figure out the reason as to why is it not working on released code base.
PS: Still struggling with caffe parser ;) 

> terminating with uncaught exception of type armnn::ParseException: Data blob at index 0 in layer conv1/mod has an unexpected size. Expected 864 elements but got 0 elements.  at function GetDataFromBlob [/abfdata/payal.anand/ARMNN/armnn-devenv/armnn/src/armnnCaffeParser/CaffeParser.cpp:116]
Aborted

**Comment by MatthewARM** [comment] 2019-04-08 08:29
Thanks @AnPay I guess there must be a bug in the release which has "gone away" in the master branch. I'll see if we can find out what it was, and maybe we'll need to patch the release.

**Comment by Azutoz** [comment] 2019-04-23 11:11
Facing the same error while trying to execute mobilenetv1.caffemodel..

Armnn Error: Data blob at index 0 in layer conv1/mod has an unexpected size. Expected 864 elements but got 0 elements.  at function GetDataFromBlob [ARMNN/armnn-devenv/armnn/src/armnnCaffeParser/CaffeParser.cpp:120]

Any leads? @MatthewARM

**Comment by MatthewARM** [comment] 2019-04-23 11:42
Thanks @Azutoz can you provide a download link for the model?

**Comment by MatthewARM** [comment] 2019-10-14 10:26
Closing this as the issue reported by @AnPay has been resolved (somehow...)

@Azutoz please create a new issue if you are still seeing a problem with the Caffe parser. Many thanks.

Matthew

**Closed by MatthewARM** 2019-10-14 10:26 UTC
