### ISSUE TITLE
Problems with quantized tflite mnist model

### ISSUE THREAD

**Issue by damiangajewski** [ARM-software/armnn#161] opened 2019-03-28 15:06 UTC
I have problem with simple dense network. I have quantized model trained in tensorflow on mnist dataset. It works good in python, but when i run it in armnn almost all predictions are 0. This is my code:
```  cpp
//
// Copyright © 2018 Arm Ltd. All rights reserved.
// See LICENSE file in the project root for full license information.
//

#include <iostream>
#include <string>
#include <fstream>
#include <vector>
#include <memory>
#include <array>
#include <algorithm>
#include <cstring>
#include "armnn/ArmNN.hpp"
#include "armnn/Exceptions.hpp"
#include "armnn/Tensor.hpp"
#include "armnn/INetwork.hpp"
#include "armnnTfLiteParser/ITfLiteParser.hpp"

#include "mnist_loader.hpp"

#define MAX_IMAGES 3000 

// Helper function to make input tensors
armnn::InputTensors MakeInputTensors(const std::pair<armnn::LayerBindingId,
    armnn::TensorInfo>& input,
    const void* inputTensorData)
{
    return { { input.first, armnn::ConstTensor(input.second, inputTensorData) } };
}

// Helper function to make output tensors
armnn::OutputTensors MakeOutputTensors(const std::pair<armnn::LayerBindingId,
    armnn::TensorInfo>& output,
    void* outputTensorData)
{
    return { { output.first, armnn::Tensor(output.second, outputTensorData) } };
}

int main(int argc, char** argv)
{
    // Default input size is one image
    unsigned int nrOfImages = 1;

    // Optimisation mode 0 = CPU Reference (unoptimised)
    // Optimisation mode 1 = CPU Accelerator
    // Optimisation mode 2 = GPU Accelerator
    unsigned int optimisationMode = 1;

    // Check program arguments
    if (argc != 3)
    {
      std::cout << "Invalid arguments. Exactly 2 arguments required." << std::endl;
      std::cout << "Example: ./mnist_tf 1 10" << std::endl;
      std::cout << "Optimisation modes: 0 for CpuRef, 1 for CpuAcc, 2 for GpuAcc" << std::endl;
      std::cout << "Input size: 1 to 2000 (number of images to predict)" << std::endl;
      return 1;
    }

// Parse input size option
    nrOfImages = std::stoi(argv[2]);
    if (!(nrOfImages > 0 && nrOfImages <= MAX_IMAGES))
    {
      std::cout << "Error: Maximum number of images is " << MAX_IMAGES << std::endl;
      return 1;
    }

    // Parse optimisation mode option
    optimisationMode = std::stoi(argv[1]);
    if (!(optimisationMode == 0 || optimisationMode == 1 || optimisationMode == 2))
    {
      std::cout << "Invalid optimisation mode." << std::endl;
      return 1;
    }

    // Import the TensorFlow model. Note: use CreateNetworkFromBinaryFile for .pb files.
    armnnTfLiteParser::ITfLiteParserPtr parser = armnnTfLiteParser::ITfLiteParser::Create();
    armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("model/quantized_model_dense.tflite");

    // Find the binding points for the input and output nodes
    armnnTfLiteParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo(0, "dense_1_input");
    armnnTfLiteParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo(0, "activation_3/Softmax");

    // Create ArmNN runtime
    armnn::IRuntime::CreationOptions options; // default options
    armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);

    // Optimize the network for a specific runtime compute device, e.g. CpuAcc, GpuAcc
    std::cout << "Optimisation mode: ";
    armnn::Compute device;
    switch(optimisationMode)
    {
      case 0: device = armnn::Compute::CpuRef; std::cout << "CpuRef" << std::endl; break;
      case 1: device = armnn::Compute::CpuAcc; std::cout << "CpuAcc" << std::endl; break;
      case 2: device = armnn::Compute::GpuAcc; std::cout << "GpuAcc" << std::endl; break;
    }

    armnn::IOptimizedNetworkPtr optNet = Optimize(*network, {device}, runtime->GetDeviceSpec());

    // Load the optimized network onto the runtime device
    armnn::NetworkId networkIdentifier;
    runtime->LoadNetwork(networkIdentifier, std::move(optNet));

    // Load multiple images from the data directory
    std::string dataDir = "data/";

    auto input = new float[nrOfImages][g_kMnistImageByteSize];
    auto output = new float[nrOfImages][10];
    auto labels = new int[nrOfImages];

for (int i = 0; i < nrOfImages; ++i)
    {
      std::unique_ptr<MnistImage> imgInfo = loadMnistImage(dataDir, i);
      if (imgInfo == nullptr)
          return 1;

      std::memcpy(input[i], imgInfo->image, sizeof(imgInfo->image));
      labels[i] = imgInfo->label;
    }

  for (int i = 0; i < nrOfImages; ++i)
    {
        for (int j = 0; j < 784; ++j) {
            std::cout << input[i][j] << " ";
        }
        std::cout << std::endl << std::endl;
    }


    // Execute network
    armnn::InputTensors inputTensor = MakeInputTensors(inputBindingInfo, &input[0]);
    armnn::OutputTensors outputTensor = MakeOutputTensors(outputBindingInfo, &output[0]);

    armnn::Status ret = runtime->EnqueueWorkload(networkIdentifier, inputTensor, outputTensor);

    // Check output and compute correct predictions
    int nrOfCorrectPredictions = 0;
    for (int i = 0; i < nrOfImages; ++i)
    {
      float max = output[i][0];
      int label = 0;

      for (int j = 0; j < 10; ++j)
      {
        // Translate 1-hot output to find integer label
        if (output[i][j] > max)
        {
          max = output[i][j];
          // std::cout << max << std::endl;
          label = j;
        }
      }
      if (label == labels[i]) nrOfCorrectPredictions++;
      std::cout << "#" << i+1 << " | Predicted: " << label << " Actual: " << labels[i] << std::endl;
    }
    std::cout << "Prediction accuracy: " << (float)nrOfCorrectPredictions/nrOfImages*100 << "%";
    std::cout << std::endl;

    delete[] input;
    delete[] output;
    delete[] labels;

    return 0;
}
```
Is it something wrong with that code?

**Comment by MatthewARM** [comment] 2019-04-01 16:46
Hi @damiangajewski I started to answer this question on https://github.com/ARM-software/ML-examples/issues/8# but thanks for reposting here as it's probably a better place for it.

The answer is that quantized networks represent an original float network, but using a quantized encoding. In your code I think you're passing 8-bit bitmap data directly in to the network without converting it to the QASYMM8 type according to the quantisation parameters in your network.

So you need to first convert your bitmap data to float, according to whatever scheme was used when the network was trainined (e.g.  [0,255] maps to [0.0f,1.0f]) then convert to the quantized type expected by your input layer. There's a `Quantize` function in include/armnn/TypesUtils.hpp that will do that on an individual value.

Hope that helps,
Matthew

**Comment by damiangajewski** [comment] 2019-04-04 12:19
Ok @MatthewARM so I've tried to do something like that:
``` cpp
auto a = armnn::Quantize<arm_compute::qasymm8_t>(input[i][j], inputScale, inputOffset);
```
for every pixel in every image.
But network still predict almost always 0. Is It good solution? I've also tried just cast values:
``` cpp
auto a = static_cast<arm_compute::qasymm8_t>(input[i][j]);
```
but results was same.

**Comment by MatthewARM** [comment] 2019-04-04 13:12
Hi @damiangajewski I'm not sure. Fundamentally you need to make sure that the input tensor you give your quantized network is a quantized version of the same tensor you would give your original floating-point network.

So the place to start is, (1) for a given pixel in your training data, how did you convert that to floating point when training?

(2) Make sure that you can run the unquantized network with your floating-point inputs.

(3) run the quantized network, and quantize your floating point inputs to QAsymm8. You should get the same output as step (2), just encoded in QAsymm8.

Hope that helps,
Matthew

**Comment by MohitB9** [comment] 2019-08-20 10:18
Hi everyone, I struggled initially while running tensorflow-lite mobilenet model from official tensorflow website. But now I have the working code using the ready-made model and want to suggest few tips to the community.
1. Mobilenet's non-quantized model needs image pre-processing as converting BGR2RGB, resizing to 256, then centre crop of 224x224, Mean subtraction and division by 128.
2. But quantised model mobilenet_v1_1.0_224_quant does not require any serious preprocessing. Just read the image, convert BGR2RGB, just resize to 224x224. Thats it! pass it as it is to network. Obviously, user needs to de-quantise the output by dividing it by 225.    

Conclusion: Info about image pre-processing should be shared with models.

**Comment by MatthewARM** [comment] 2019-11-21 22:08
Thanks @MohitB9 that's a good example. The issue is that without knowing how the model was trained,  the user can't know how to prepare the input data for the model.  I strongly suspect this is causing the issue that @damiangajewski is seeing. 

Unfortunately this is not something that Arm NN can do automatically as there is no way to encode the necessary metadata in the model.

@damiangajewski I would suggest that you try getting the floating-point version working first, as that's easier to set up, then add in quantization when you've got a working system?

**Comment by MatthewARM** [comment] 2020-01-14 21:10
Closing this as @MohitB9 has provided a good answer.

**Closed by MatthewARM** 2020-01-14 21:10 UTC
