### ISSUE TITLE
Does  ARM NN SDK support OpenGL  ?

### ISSUE THREAD

**Issue by pavanonchip** [ARM-software/armnn#85] opened 2018-10-22 10:28 UTC
Hi 
   In process of cross compiling  arm-nn-sdk, i found two flags  which are input to cmake.

If you are supporting NEON, add this argument to the CMake command:
-DARMCOMPUTENEON=1
If you are supporting OpenCL, add this argument to the CMake command:
-DARMCOMPUTECL=1

above lines are from PDF attached below  

similar is their any FLAG to enable arm-nn-sdk to support  OpenGL......?

[Configuring the Arm NN SDK build environment for TensorFlow(1).pdf](https://github.com/ARM-software/armnn/files/2500968/Configuring.the.Arm.NN.SDK.build.environment.for.TensorFlow.1.pdf)

Thanks in advance for your support

**Comment by pavanonchip** [comment] 2018-10-22 10:41
-

**Comment by MatthewARM** [comment] 2018-10-30 12:58
Sorry @pavanonchip , somehow we missed this question. I'll mark this a duplicate of the question you asked today.

**Comment by MatthewARM** [comment] 2018-10-30 12:58
Duplicate of https://github.com/ARM-software/armnn/issues/93

**Closed** 2018-10-30 12:59 UTC
Labels: Duplicate
